export default {
    WELCOME_MESSAGE: "WELCOME_MESSAGE",
    WELCOME_MESSAGE_RESPONSE: "WELCOME_MESSAGE_RESPONSE",
    APP_BTN_TYPES:{
        JIMMY:"JIMMY",
    },
    MARK_ATTENDANCE:"MARK_ATTENDANCE",
    ATTANDANCE_MARKED_SUCCESSFULL:"ATTANDANCE_MARKED_SUCCESSFULL",
    TODAYS_ATTENDANCE_DONE:"TODAYS_ATTENDANCE_DONE",
    MARKED_CHECK_OUT:"MARKED_CHECK_OUT",
    MARKING_CHECK_OUT_IN_PROGRESS:"MARKING_CHECK_OUT_IN_PROGRESS",
    COMPLETE_CHECKOUT:"COMPLETE_CHECKOUT",
    IN:"IN",
    OUT:"OUT",
}