export default {
    WELCOME_MESSAGE: "WELCOME_MESSAGE",
    WELCOME_MESSAGE_RESPONSE: "WELCOME_MESSAGE_RESPONSE",
    APP_BTN_TYPES:{
        JIMMY:"JIMMY",
    },
    MARK_ATTENDANCE:"MARK_ATTENDANCE",
    ATTANDANCE_MARKED_SUCCESSFULL:"ATTANDANCE_MARKED_SUCCESSFULL",
    TODAYS_ATTENDANCE_DONE:"TODAYS_ATTENDANCE_DONE",
    MARKED_CHECK_OUT:"MARKED_CHECK_OUT",
    MARKING_CHECK_OUT_IN_PROGRESS:"MARKING_CHECK_OUT_IN_PROGRESS",
    COMPLETE_CHECKOUT:"COMPLETE_CHECKOUT",
    SAVE_CURRENT_URL:"SAVE_CURRENT_URL",
    CURRENT_URL_SAVED:"CURRENT_URL_SAVED",
    ON_TAB_FOCUS:"ON_TAB_FOCUS",
    START_WAITING_FOR_VALID_HOUR:"START_WAITING_FOR_VALID_HOUR",
    AUTO_JIMMYAJA_CHECKOUT_ORDER:"AUTO_JIMMYAJA_CHECKOUT_ORDER",
    IN:"IN",
    OUT:"OUT",
    AUTO_CHECKOUT_USER_CHOICE:"AUTO_CHECKOUT_USER_CHOICE",
    ENUMS:{
        USER_CHOICE:{
            AUTO_CHECKOUT:{
                DENIED:0,
                ALLOWED:1,
            }
        }
    },
    CONFIG:{
        GET:"CONFIG.GET",
        GET_SERVER:"CONFIG.GET.SERVER",
        SET:"CONFIG.SET",
        SET_SERVER:"CONFIG.SET.SERVER",
    }

}